/* PW2_manual_do_calouro */

/* DEVE SER EXECUTADO ANTES DE CRIAR A TABELA */
CREATE DATABASE PW2_manual_do_calouro;

/* SELECIONE O BANCO DE DADOS ANTES DE RODAR ESSE BLOCO */
CREATE TABLE Usuarios (
    id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    login VARCHAR(100) NOT NULL,
    senha VARCHAR(250) NOT NULL,
    foto_perfil VARCHAR(300) DEFAULT NULL
);